### Develop LSTM Models For Univariate Time Series Forecasting

In [1]:

# univariate lstm example
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten


In [2]:
# preparing independent and dependent features
def prepare_data(timeseries_data, n_features):
	X, y =[],[]
	for i in range(len(timeseries_data)):
		# find the end of this pattern
		end_ix = i + n_features
		# check if we are beyond the sequence
		if end_ix > len(timeseries_data)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [3]:
# define input sequence
timeseries_data = [110, 125, 133, 146, 158, 172, 187, 196, 210]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

In [4]:
print(X),print(y)

[[110 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]]
[146 158 172 187 196 210]


(None, None)

In [5]:
X.shape

(6, 3)

In [6]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

### Building LSTM Model

In [7]:

# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=300, verbose=1)


Epoch 1/300
1/1 [==============================] - 2s 2s/step - loss: 32249.2812
Epoch 2/300
1/1 [==============================] - 0s 5ms/step - loss: 31777.9121
Epoch 3/300
1/1 [==============================] - 0s 4ms/step - loss: 31306.3438
Epoch 4/300
1/1 [==============================] - 0s 6ms/step - loss: 30843.9395
Epoch 5/300
1/1 [==============================] - 0s 8ms/step - loss: 30396.4160
Epoch 6/300
1/1 [==============================] - 0s 4ms/step - loss: 29965.2051
Epoch 7/300
1/1 [==============================] - 0s 8ms/step - loss: 29552.6016
Epoch 8/300
1/1 [==============================] - 0s 9ms/step - loss: 29158.5566
Epoch 9/300
1/1 [==============================] - 0s 8ms/step - loss: 28777.6348
Epoch 10/300
1/1 [==============================] - 0s 6ms/step - loss: 28402.6348
Epoch 11/300
1/1 [==============================] - 0s 5ms/step - loss: 28033.3672
Epoch 12/300
1/1 [==============================] - 0s 8ms/step - loss: 27668.0449
Epoch 13/300
1

1/1 [==============================] - 0s 8ms/step - loss: 17.7143
Epoch 102/300
1/1 [==============================] - 0s 5ms/step - loss: 17.3103
Epoch 103/300
1/1 [==============================] - 0s 8ms/step - loss: 17.0635
Epoch 104/300
1/1 [==============================] - 0s 9ms/step - loss: 16.9670
Epoch 105/300
1/1 [==============================] - 0s 4ms/step - loss: 16.9937
Epoch 106/300
1/1 [==============================] - 0s 8ms/step - loss: 17.1042
Epoch 107/300
1/1 [==============================] - 0s 8ms/step - loss: 17.2554
Epoch 108/300
1/1 [==============================] - 0s 6ms/step - loss: 17.4060
Epoch 109/300
1/1 [==============================] - 0s 8ms/step - loss: 17.5191
Epoch 110/300
1/1 [==============================] - 0s 7ms/step - loss: 17.5649
Epoch 111/300
1/1 [==============================] - 0s 5ms/step - loss: 17.5359
Epoch 112/300
1/1 [==============================] - 0s 5ms/step - loss: 17.4442
Epoch 113/300
1/1 [=======================

1/1 [==============================] - 0s 8ms/step - loss: 14.4571
Epoch 203/300
1/1 [==============================] - 0s 4ms/step - loss: 14.3998
Epoch 204/300
1/1 [==============================] - 0s 4ms/step - loss: 14.3435
Epoch 205/300
1/1 [==============================] - 0s 8ms/step - loss: 14.2853
Epoch 206/300
1/1 [==============================] - 0s 8ms/step - loss: 14.2237
Epoch 207/300
1/1 [==============================] - 0s 8ms/step - loss: 14.1607
Epoch 208/300
1/1 [==============================] - 0s 8ms/step - loss: 14.0989
Epoch 209/300
1/1 [==============================] - 0s 8ms/step - loss: 14.0386
Epoch 210/300
1/1 [==============================] - 0s 8ms/step - loss: 13.9779
Epoch 211/300
1/1 [==============================] - 0s 8ms/step - loss: 13.9150
Epoch 212/300
1/1 [==============================] - 0s 8ms/step - loss: 13.8493
Epoch 213/300
1/1 [==============================] - 0s 9ms/step - loss: 13.7810
Epoch 214/300
1/1 [=======================

### Predicting For the next 10 data

In [10]:
# demonstrate prediction for next 10 days
x_input = np.array([187, 196, 210])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

print(lst_output)

[223.83313]
1 day input [196.         210.         223.83312988]
1 day output [[235.75165]]
2 day input [210.         223.83312988 235.75164795]
2 day output [[250.13112]]
3 day input [223.83313 235.75165 250.13112]
3 day output [[264.30017]]
4 day input [235.75165 250.13112 264.30017]
4 day output [[278.39417]]
5 day input [250.13112 264.30017 278.39417]
5 day output [[293.89194]]
6 day input [264.30017 278.39417 293.89194]
6 day output [[309.5374]]
7 day input [278.39417 293.89194 309.5374 ]
7 day output [[325.72476]]
8 day input [293.89194 309.5374  325.72476]
8 day output [[342.89752]]
9 day input [309.5374  325.72476 342.89752]
9 day output [[360.52933]]
[223.83313, 235.75165, 250.13112, 264.30017, 278.39417, 293.89194, 309.5374, 325.72476, 342.89752, 360.52933]


In [11]:
timeseries_data

[110, 125, 133, 146, 158, 172, 187, 196, 210]

In [12]:
len(timeseries_data)

9

In [13]:
lst_output

[223.83313,
 235.75165,
 250.13112,
 264.30017,
 278.39417,
 293.89194,
 309.5374,
 325.72476,
 342.89752,
 360.52933]

### Visualizaing The Output

In [15]:
import matplotlib.pyplot as plt

In [16]:
day_new=np.arange(1,10)
day_pred=np.arange(10,20)

In [ ]:
plt.plot(day_new,timeseries_data)
plt.plot(day_pred,lst_output)
